name: PR Checks
on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9.13.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Check formatting
        run: pnpm prettier --check .
        
      - name: Type check
        run: pnpm run typecheck
        
      - name: Lint
        run: pnpm run lint
        
      - name: Test
        run: pnpm run test